USE DB_Bank

CREATE TABLE Banks
(
	Id INT PRIMARY KEY IDENTITY,
	BankName VARCHAR(50) UNIQUE NOT NULL
)

CREATE TABLE Cities
(
	Id INT PRIMARY KEY IDENTITY,
	CityName VARCHAR(30) UNIQUE NOT NULL
)

CREATE TABLE BanksLocation
(
	BankId INT REFERENCES Banks(Id) NOT NULL,
	CityId INT REFERENCES Cities(Id) NOT NULL,
)

CREATE TABLE SocialStatuses
(
	Id INT PRIMARY KEY IDENTITY,
	StatusName VARCHAR(50) UNIQUE NOT NULL
)

CREATE TABLE Clients
(
	Id INT PRIMARY KEY IDENTITY,
	FullName VARCHAR(50) UNIQUE NOT NULL,
	StatusId INT REFERENCES SocialStatuses(Id) NOT NULL
)

CREATE TABLE Accounts
(
	Id INT PRIMARY KEY IDENTITY,
	AccountName VARCHAR(30) UNIQUE NOT NULL,
	AccountNumber VARCHAR(28) UNIQUE NOT NULL,
	BankId INT REFERENCES Banks(Id) NOT NULL,
	ClientId INT REFERENCES Clients(Id) NOT NULL,
)

ALTER TABLE Accounts
ADD Balance MONEY

CREATE TABLE Cards
(
	Id INT PRIMARY KEY IDENTITY,
	CardNumber VARCHAR(19) UNIQUE NOT NULL,
	AccountId INT REFERENCES Accounts(Id) NOT NULL
)

ALTER TABLE Cards
ADD CardBalance MONEY
